<b>Новая заявка с сайта {$_modx->config.site_url}</b>

<table>
    <tbody>
    <tr>
        <td>
            <b>Имя:</b>
        </td>
        <td>
            {$name}
        </td>
    </tr>
    <tr>
        <td>
            <b>Телефон:</b>
        </td>
        <td>
            {$phone}
        </td>
    </tr>
    <tr>
        <td>
            <b>Сообщение:</b>
        </td>
        <td>
            {$message}
        </td>
    </tr>
    </tbody>
</table>